### ISSUE TITLE
hot-fix: サイトのロードが終わらずページが表示されない不具合

### ISSUE THREAD

**Issue by kazuemon** [stopcovid19-okayama/covid19#2204]
## 起こっている問題 / The Problem
```
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://okayama.stopcovid19.jp/_nuxt/7485518.js:2:41273)
    at m (https://okayama.stopcovid19.jp/_nuxt/7485518.js:2:54196)
    at https://okayama.stopcovid19.jp/_nuxt/7485518.js:2:53453
    at v (https://okayama.stopcovid19.jp/_nuxt/7485518.js:2:53685)
    at w (https://okayama.stopcovid19.jp/_nuxt/7485518.js:2:54282)
    at R (https://okayama.stopcovid19.jp/_nuxt/7485518.js:2:57668)
    at R (https://okayama.stopcovid19.jp/_nuxt/7485518.js:2:57603)
    at f.__patch__ (https://okayama.stopcovid19.jp/_nuxt/7485518.js:2:58080)
    at f.t._update (https://okayama.stopcovid19.jp/_nuxt/7485518.js:2:35019)
    at f.r (https://okayama.stopcovid19.jp/_nuxt/7485518.js:2:65483)
```

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://okayama.stopcovid19.jp/ にアクセス

## 動作環境・ブラウザ / Environment
- Chrome 87.0.4280.88 (64bit) / Windows 10

**Comment by kazuemon** [comment]
![image](https://user-images.githubusercontent.com/12812934/103257835-34a52800-49d6-11eb-8434-2005586f1cc2.png)

**Comment by kazuemon** [comment]
`development` では問題なし、`master` 上で `yarn dev` すると上記warnのみ発生

**Comment by kazuemon** [comment]
`yarn generate` で同様の現象を確認
![2020-12-29 13_34_55-県内の最新感染動向 _ 岡山県 新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/12812934/103259032-0aa23480-49db-11eb-850f-da704673ad9a.png)

generate 時に確認されたエラーログ
![2020-12-29 13_36_10-設定 - 未設定 (ワークスペース) - Visual Studio Code](https://user-images.githubusercontent.com/12812934/103259042-17268d00-49db-11eb-9c27-ac8a95c67844.png)

**Comment by kazuemon** [comment]
ref: #2202

**Comment by kazuemon** [comment]
解消されましたのでクローズします。
